package com.bikash.fintechsettlement.ledger.domain.error;

public enum LedgerErrorCode {
    INVALID_ACCOUNT,
    DUPLICATE_ACCOUNT,
    UNKNOWN_ACCOUNT,
    ACCOUNT_CLOSED,
    INVALID_ENTRY,
    UNBALANCED_TRANSACTION,
    ARITHMETIC_OVERFLOW,
    DUPLICATE_TRANSACTION,
    POSTING_IDEMPOTENCY_CONFLICT,
    SOURCE_FINANCIAL_EVENT_CONFLICT,
    INVALID_POSTING_POLICY,
    REVERSAL_NOT_ALLOWED
}
